<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors [
<!ELEMENT authors (author)*>
<!ELEMENT author (name , nick , email , role+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT role (#PCDATA)>
]>

<!-- a few comments:
- name: the order is: family, first, middle
- nick: irc nick, case sensitive, or you won't get op ;-)
- email: where you're _reachable_ (@frugalware.org is not required)

if you modify this file, be sure it's still valid - xmllint is your friend
-->

<authors>
	<author>
		<name>Craciunescu, Gabriel</name>
		<nick>crazy||</nick>
		<email>crazy@frugalware.org</email>
		<role>KDE and KOffice maintainer</role>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Csécsy, László</name>
		<nick>boobaa</nick>
		<email>boobaa@ajrg.hu</email>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Czövek, Károly</name>
		<nick>slin</nick>
		<email>slinky@rei.keni.hu</email>
		<role>network category maintainer</role>
		<role>bug tracking system server hoster</role>
	</author>
	<author>
		<name>Gondor, Viktor</name>
		<nick>Nadfoka</nick>
		<email>nadfoka@frugalware.org</email>
		<role>frugalware artwork</role>
	</author>
	<author>
		<name>Gosalia, Priyank</name>
		<nick>priyank</nick>
		<email>priyank@frugalware.org</email>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Habermehl, Marcus</name>
		<nick>BMH1980</nick>
		<email>bmh1980@frugalware.org</email>
		<role>package maintainer</role>
		<role>graphical config tools</role>
	</author>
	<author>
		<name>Hamar, Christian</name>
		<nick>krix</nick>
		<email>krics@linuxforum.hu</email>
		<role>x86_64 porter</role>
		<role>GNOME co-maintainer</role>
		<role>bugfixer, etc...</role>
	</author>
	<author>
		<name>Kápolnási, Tamás</name>
		<nick>aThom</nick>
		<email>ktamas@tdc.hu</email>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Kimpe, David</name>
		<nick>DNAku</nick>
		<email>DNAku@frugalware.org</email>
		<role>package maintainer</role>
		<role>PPC porter</role>
	</author>
	<author>
		<name>Kovács, János</name>
		<nick>janny</nick>
		<email>janny@frugalware.org</email>
		<role>OpenOffice.org maintainer</role>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Nagy, Bence</name>
		<nick>gimb</nick>
		<email>nagybence@tipogral.hu</email>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Nemeth, Miklós</name>
		<nick>desco</nick>
		<email>desco@frugalware.org</email>
		<role>x86_64 porter</role>
		<role>wx{gtk,python,glade} maintainer</role>
		<role>GNOME co-maintainer</role>
	</author>
	<author>
		<name>Smith, Alex</name>
		<nick>AlexExtreme</nick>
		<email>alex.extreme2@gmail.com</email>
		<role>webapps maintainer</role>
		<role>xen maintainer</role>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Szalai, Zsolt</name>
		<nick>xbit`</nick>
		<email>xbit.lists@chello.hu</email>
		<role>perl and its modules</role>
	</author>
	<author>
		<name>Vajna, Miklós</name>
		<nick>vmiklos</nick>
		<email>vmiklos@frugalware.org</email>
		<role>Frugalware core</role>
		<role>devel category maintainer</role>
		<role>CD/DVD images maintainer</role>
		<role>dns, ftp, rsync, mailman admin</role>
	</author>
	<author>
		<name>Vasas, Krisztián</name>
		<nick>IroNiQ</nick>
		<email>iron@frugalware.org</email>
		<role>Hungarian translations</role>
		<role>homepage maintainer</role>
		<role>x86_64 server administrator</role>
		<role>x86_64 porter</role>
		<role>Xfce maintainer</role>
		<role>package maintainer</role>
	</author>
	<author>
		<name>Vöröskői, András</name>
		<nick>voroskoi</nick>
		<email>voroskoi@frugalware.org</email>
		<role>multimedia category maintainer</role>
		<role>e17 maintainer</role>
	</author>
</authors>
