<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE authors [
<!ELEMENT authors (author)*>
<!ELEMENT author (name , nick , email , role+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT role (#PCDATA)>
]>

<!-- if you modify this file, be sure it's still valid - xmllint is your friend
-->

<authors>
	<author>
		<name>Balázs, Botond</name>
		<nick>Arcturus</nick>
		<email>arcturus_rocks@freemail.hu</email>
		<role>German translations</role>
	</author>
	<author>
		<name>Barabás, Péter</name>
		<nick>z0d</nick>
		<email>z0d@artifact.hu</email>
		<role>package contributions</role>
	</author>
	<author>
		<name>Gondor, Viktor</name>
		<nick>Nadfoka</nick>
		<email>nadfoka@frugalware.org</email>
		<role>Frugalware artwork</role>
	</author>
	<author>
		<name>Kiss, Zoltán</name>
		<nick>djsmiley</nick>
		<email>djsmiley@inflame.hu</email>
		<role>package contributions</role>
	</author>
	<author>
		<name>Nági, Zsófi</name>
		<nick>killahbunny</nick>
		<email>nagizs@yahoo.com</email>
		<role>English spellchecks</role>
	</author>
	<author>
		<name>Pállya, Krisztián</name>
		<nick>PChris</nick>
		<email>pchris@enternet.hu</email>
		<role>Italian translations</role>
	</author>
	<author>
		<name>Sipka, Dániel</name>
		<nick>MSD</nick>
		<email>no1msd@gmail.com</email>
		<role>Frugalware 0.2 artwork</role>
	</author>
	<author>
		<name>Tóth, Róbert</name>
		<nick>trobi</nick>
		<email>t.r@zmail.sk</email>
		<role>Slovak translations</role>
	</author>
	<author>
		<name>Leite, Pedro</name>
		<nick>pedro_jsl</nick>
		<email>pedro.leite@gmail.com</email>
		<role>Brazillian translations</role>
	</author>
</authors>
