<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE articles [
<!ELEMENT articles (article)*>
<!ELEMENT article (date , language , where, title , link)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT where (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT link (#PCDATA)>
]>

<!-- if you modify this file, be sure it's still valid - xmllint is your friend
-->

<articles>
	<article>
		<date>2008-01-16</date>
		<language>Hungarian</language>
		<where>Szabad szoftver esték (Free Software Evenings)</where>
		<title>Frugalware versus other distributions</title>
		<link>http://video.google.com/videoplay?docid=-8129703727993942585</link>
	</article>
	<article>
		<date>2007-12-11</date>
		<language>English</language>
		<where>Open Review</where>
		<title>Frugalware 0.7 Review</title>
		<link>http://simplyjat.blogspot.com/2007/12/frugalware-07-review.html</link>
	</article>
	<article>
		<date>2007-10-22</date>
		<language>French</language>
		<where>FRLinux.net</where>
		<title>Frugalware 0.7 (Sayshell)</title>
		<link>http://frlinux.net/?section=distributions&amp;article=201</link>
	</article>
	<article>
		<date>2007-04-20</date>
		<language>French</language>
		<where>FRLinux.net</where>
		<title>Frugalware 0.6 (Terminus)</title>
		<link>http://frlinux.net/?section=distributions&amp;article=190</link>
	</article>
	<article>
		<date>2007-03-02</date>
		<language>French</language>
		<where>Linux+</where>
		<title>Distributions GNU/Linux moins connues</title>
		<link>http://lpmagazine.org/fr/linuxplus/issues/3_2007.html</link>
	</article>
	<article>
		<date>2007-01-24</date>
		<language>French</language>
		<where>Blogspot</where>
		<title>Coup de coeur!</title>
		<link>http://ltjmax.blogspot.com/2007/01/coup-de-coeur.html</link>
	</article>
	<article>
		<date>2006-10-17</date>
		<language>English</language>
		<where>Polishlinux.org</where>
		<title>Review: Frugalware 0.5 (Siwenna)</title>
		<link>http://polishlinux.org/linux/frugalware/review-frugalware-0-5-siwenna/</link>
	</article>
	<article>
		<date>2006-10-15</date>
		<language>Polish</language>
		<where>Polishlinux.org</where>
		<title>Recenzja: Frugalware 0.5 (Siwenna)</title>
		<link>http://jakilinux.org/linux/frugalware/recenzja-frugalware-0-5-siwenna/</link>
	</article>
	<article>
		<date>2006-09-19</date>
		<language>Spanish</language>
		<where>GNEBU</where>
		<title>Breve mirada a Frugalware 0.5</title>
		<link>http://www.gnebu.es/articulo.php?id=18</link>
	</article>
	<article>
		<date>2006-05-22</date>
		<language>English</language>
		<where>DistroWatch</where>
		<title>Interview: Miklós Vajna, Frugalware Linux</title>
		<link>http://distrowatch.com/weekly.php?issue=20060522#interview</link>
	</article>
	<article>
		<date>2006-05-10</date>
		<language>English</language>
		<where>Linux.com</where>
		<title>Review: Frugalware Linux</title>
		<link>http://www.linux.com/article.pl?sid=06/04/27/1947239</link>
	</article>
	<article>
		<date>2006-04-26</date>
		<language>English</language>
		<where>Slack Addict</where>
		<title>Interview with Frugalware Linux developer, VMiklos</title>
		<link>http://www.openaddict.com/interview_with_frugalware_linux_developer_vmiklos.html</link>
	</article>
	<article>
		<date>2006-04-18</date>
		<language>French</language>
		<where>QuebecOS</where>
		<title>Frugalware 0.4: toute la puissance de votre processeur!</title>
		<link>http://www.quebecos.com/modules/sections/index.php?op=viewarticle&amp;artid=45</link>
	</article>
	<article>
		<date>2006-04-18</date>
		<language>English</language>
		<where>NewsForge</where>
		<title>My desktop OS: Frugalware</title>
		<link>http://os.newsforge.com/article.pl?sid=06/04/12/1555253</link>
	</article>
	<article>
		<date>2006-04-06</date>
		<language>English</language>
		<where>Wikinews</where>
		<title>Frugalware Linux Pushes Forward</title>
		<link>http://en.wikinews.org/wiki/Wikinews_interviews_Frugalware_Linux_founder</link>
	</article>
	<article>
		<date>2006-03-06</date>
		<language>English</language>
		<where>OSDir</where>
		<title>Frugalware Linux 0.4 RC1 Screenshot Tour</title>
		<link>http://www.osdir.com/Article8370.phtml</link>
	</article>
	<article>
		<date>2005-07-06</date>
		<language>English</language>
		<where>LinuxQuestions</where>
		<title>Reviews - 0.2 Aurora</title>
		<link>http://www.linuxquestions.org/reviews/showproduct.php/product/565</link>
	</article>
	<article>
		<date>2005-06-26</date>
		<language>English</language>
		<where>Tuxmachines</where>
		<title>For the best in today's fashions: Frugalware</title>
		<link>http://www.tuxmachines.org/node/1501</link>
	</article>
	<article>
		<date>2005-06-10</date>
		<language>English</language>
		<where>NewsForge</where>
		<title>My Workstation OS: Frugalware</title>
		<link>http://os.newsforge.com/os/05/06/03/2046247.shtml</link>
	</article>
	<article>
		<date>2005-05-09</date>
		<language>English</language>
		<where>DistroWatch</where>
		<title>Featured distribution of the week: Frugalware Linux</title>
		<link>http://distrowatch.com/weekly.php?issue=20050509#fdow</link>
	</article>
	<article>
		<date>2005-04-28</date>
		<language>Hungarian</language>
		<where>jox</where>
		<title>Interview with Frugalware Linux leader, developed in Hungary</title>
		<link>http://www.jox.hu/cikkek/141/12</link>
	</article>
	<article>
		<date>2004-11-03</date>
		<language>Hungarian</language>
		<where>HUP</where>
		<title>Interview with Frugalware project leader</title>
		<link>http://hup.hu/node/7264</link>
	</article>
</articles>
