<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE news [
<!ELEMENT news (post)*>
<!ELEMENT post (id, title, date, author, editedby*, content)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ELEMENT editedby (name, date)>
<!ELEMENT name (#PCDATA)>
]>
<news>
	<post>
		<id>2</id>
		<title>second test post</title>
		<date>Fri May 12 21:38:39 CEST 2006</date>
		<author>IroNiQ</author>
		<content><![CDATA[
			This is the second test post.<br />
			It can have more than one line.<br />
			]]>
		</content>
	</post>
	<post>
		<id>1</id>
		<title>first test post</title>
		<date>Fri May 12 21:38:39 CEST 2006</date>
		<author>IroNiQ</author>
		<editedby>
			<name>VMiklos</name>
			<date>Fri May 12 22:11:03 CEST 2006</date>
		</editedby>
		<editedby>
			<name>boobaa</name>
			<date>Fri May 12 22:11:18 CEST 2006</date>
		</editedby>
		<content><![CDATA[
			This is a test post.<br />
			It can have more than one line, too.<br />
			]]>
		</content>
	</post>
</news>
