<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fsas [
<!ELEMENT fsas (fsa)*>
<!ELEMENT fsa (id , date , author, package, vulnerable , unaffected , bts , cve , desc)>
<!-- must be an integer -->
<!ELEMENT id (#PCDATA)>
<!-- in YYYY-MM-DD format -->
<!ELEMENT date (#PCDATA)>
<!-- your darcs account, if an error occures, a mail will be sent to author@frugalware.org -->
<!ELEMENT author (#PCDATA)>
<!-- package name, without group, version, etc -->
<!ELEMENT package (#PCDATA)>
<!-- the old version -->
<!ELEMENT vulnerable (#PCDATA)>
<!-- the new (backported) version -->
<!ELEMENT unaffected (#PCDATA)>
<!-- bts url -->
<!ELEMENT bts (#PCDATA)>
<!-- cve url -->
<!ELEMENT cve (#PCDATA)>
<!-- description, can be more than one line -->
<!ELEMENT desc (#PCDATA)>
]>

<!-- if you modify this file, be sure it's still valid - xmllint is your friend
-->

<fsas>
	<fsa>
		<id>1</id>
		<date>2006-09-03</date>
		<author>vmiklos</author>
		<package>zlib</package>
		<vulnerable>1.2.3-1</vulnerable>
		<unaffected>1.2.3-2wanda1</unaffected>
		<bts>http://bugs.frugalware.org/983</bts>
		<cve>http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2002-0059</cve>
		<desc><![CDATA[
			zlib is a compression/decompression library.<br />
			This is just a fake FSA for testing purposes.<br />
			]]>
		</desc>
	</fsa>
</fsas>
