<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE teams [
	<!ELEMENT teams (team)*>
	<!ELEMENT team (name , email? , description? , maintainer+ , group+)>
	<!ELEMENT maintainer (name? , email , role*)>

	<!ELEMENT name (#PCDATA)>
	<!ELEMENT email (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT group (#PCDATA)>
	<!ELEMENT role (#PCDATA)>
]>
<teams>
	<team>
		<name>base</name>
		<description>Frugalware core</description>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
                <maintainer>
                	<email>crazy@frugalware.org</email>
                	<role>x86_64 porting</role>
                </maintainer>
		<maintainer>
			<email>gimb@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>athom@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>slin@frugalware.org</email>
			<role>grsec</role>
		</maintainer>
		<group>base</group>
		<group>devel</group>
	</team>
	<team>
		<name>kernel</name>
		<description>kernel packages</description>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
			<role>xen packages</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<group>base</group>
	</team>
	<team>
		<name>lib</name>
		<description>base libraries</description>
		<maintainer>
			<email>xbit@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>athom@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<group>lib</group>
	</team>
	<team>
		<name>apps</name>
		<description>cli applications</description>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>slin@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>gimb@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>athom@frugalware.org</email>
		</maintainer>
		<group>apps</group>
		<group>xapps</group>
	</team>
	<team>
		<name>network</name>
		<description>network packages</description>
		<maintainer>
			<email>iron@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>slin@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>gimb@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>athom@frugalware.org</email>
		</maintainer>
		<group>network</group>
	</team>
	<team>
		<name>multimedia</name>
		<description>cd and song players, codecs, encoders</description>
		<maintainer>
			<email>janny@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org></email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<group>multimedia</group>
		<group>xmultimedia</group>
	</team>
	<team>
		<name>gtk</name>
		<description>gnome, xfce, gtk-related xapps</description>
		<maintainer>
			<email>iron@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
                <maintainer>
                	<email>crazy@frugalware.org</email>
                	<role>x86_64 porting</role>
                </maintainer>
                <maintainer>
                        <email>gimb@frugalware.org</email>
                </maintainer>
		<group>gnome</group>
		<group>xfce4</group>
		<group>xapps</group>
		<group>locale</group>
	</team>
	<team>
		<name>qt</name>
		<description>qt and kde</description>
		<maintainer>
			<email>athom@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>janny@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<group>kde</group>
		<group>locale</group>
	</team>
	<team>
		<name>webapps</name>
		<description>cmses, wikis, forums, etc.</description>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<group>network</group>
	</team>
	<team>
		<name>perl</name>
		<description>perl and its modules</description>
		<maintainer>
			<email>xbit@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<group>devel</group>
	</team>
	<team>
		<name>python</name>
		<description>python and python related apps</description>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<group>devel</group>
		<group>xapps</group>
	</team>
	<team>
		<name>e17</name>
		<description>enlightenment window manager v0.17</description>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<group>e17</group>
	</team>
	<team>
		<name>games</name>
		<description>game packages</description>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
    </maintainer>
    <maintainer>
      <email>priyank@frugalware.org</email>
      <role>i686 porting</role>
    </maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>gimb@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<group>games</group>
	</team>
	<team>
		<name>rox</name>
		<description>The ROX desktop</description>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
                <maintainer>
                	<email>crazy@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<group>rox</group>
	</team>
	<team>
		<name>xorg</name>
		<description>X.Org packages &amp; drivers</description>
		<maintainer>
			<email>krix@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>nvidia binary driver</role>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
			<role>ati binary driver</role>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalare.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>gimb@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<group>x11</group>
	</team>
	<team>
		<name>xlib</name>
		<description>desktop environment independent libraries</description>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>bmh1980@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<maintainer>
			<email>boobaa@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>voroskoi@frugalware.org</email>
		</maintainer>
                <maintainer>
                        <email>janny@frugalware.org</email>
                </maintainer>
		<maintainer>
			<email>alex@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>desco@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>crazy@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>priyank@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>iron@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<group>xlib</group>
	</team>
	<team>
		<name>emul</name>
		<description>emul packages maintaince</description>
		<maintainer>
			<email>krix@frugalware.org</email>
		</maintainer>
		<group>emul</group>
	</team>
	<!-- <team>
		<name>skel</name>
		<description>one-line brief description</description>
		<maintainer>
			<email>someone@frugalware.org</email>
		</maintainer>
		<maintainer>
			<email>vmiklos@frugalware.org</email>
			<role>i686 porting</role>
		</maintainer>
		<maintainer>
			<email>krix@frugalware.org</email>
			<role>x86_64 porting</role>
		</maintainer>
		<maintainer>
			<email>dnaku@frugalware.org</email>
			<role>ppc porting</role>
		</maintainer>
		<group>skel</group>
	</team> -->
</teams>
